spring:
  application:
    name: batch
  profiles:
    active: ${SPRING_PROFILE}
    group:
      dev:
        - kubernetes
      prod:
        - kubernetes
  mongodb:
    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URI}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_DB}&authMechanism=SCRAM-SHA-1
  data:
    redis:
      host: ${REDIS_URI}
      port: ${REDIS_PORT}
      database: ${REDIS_DB}
      password: ${REDIS_PASSWORD}

doriball:
  management:
    window_days: ${WINDOW_DAYS}
    chunk_size: ${CHUNK_SIZE}

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

doriball:
  management:
    webhook_url: ${WEBHOOK_URL}

---

spring:
  config:
    activate:
      on-profile: prod

doriball:
  management:
    webhook_url: ${WEBHOOK_URL}

---
