server:
  port: 8083

spring:
  application:
    name: admin
  profiles:
    active: ${SPRING_PROFILE}
    group:
      dev:
        - kubernetes
      prod:
        - kubernetes
  web:
    resources:
      add-mappings: true
  mongodb:
    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URI}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_DB}&authMechanism=SCRAM-SHA-1


doriball:
  management:
    admin_username: ${ADMIN_USERNAME}
    admin_password: ${ADMIN_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

---


---

