server:
  port: 8082
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
  servlet:
    context-path: /api

spring:
  application:
    name: calendar
  profiles:
    active: ${SPRING_PROFILE}
    group:
      dev:
        - kubernetes
      prod:
        - kubernetes
  web:
    resources:
      add-mappings: false
  mongodb:
    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URI}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_DB}&authMechanism=SCRAM-SHA-1
  data:
    redis:
      host: ${REDIS_URI}
      port: ${REDIS_PORT}
      database: ${REDIS_DB}
      password: ${REDIS_PASSWORD}

doriball:
  management:
    cache_ttl:
      regions: ${TTL_REGIONS:1d}
      events: ${TTL_EVENTS:6h}
      stores: ${TTL_STORES:1d}
      store_detail: ${TTL_STORE_DETAIL:1d}
      notices: ${TTL_NOTICES:1d}
      notice_detail: ${TTL_NOTICE_DETAIL:1d}
#    jwt: ${JWT_SECRET}

---

spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: WARN

---