name: Admin Dev CI / CD Pipeline
on:
  push:
    branches:
      - main
    paths:
      - module-admin
      - .github/workflows/dev-admin-cicd.yml

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Full CI / CD Step
        uses: doriball/doriball-github-actions/.github/actions/backend/integration/backend-cicd@main
        with:
          env-name: dev
          service-name: minileague-calendar-admin
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          java-version: 21
          distribution: temurin
          working-directory: module-admin
          build-command: ./gradlew :module-calendar:clean :module-calendar:bootJar
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker-repository: mrcocoball/minileague-calendar-admin
          tag-prefix: dev
          dockerfile-directory: module-admin
          gitops-repository: git@github.com:doriball/minileague-calendar-infrastructure.git
          gitops-branch: main
          gitops-values-directory: environments/dev/apps/admin-values.yml
          ssh-key: ${{ secrets.GITOPS_SSH_KEY }}
          commit-message: "chore: admin dev image update"
