name: Batch Prod CI / CD Pipeline
on:
  push:
    branches:
      - main
    paths:
      - module-batch/**
      - .github/workflows/prod-batch-cicd.yml

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Full CI / CD Step
        uses: doriball/doriball-github-actions/.github/actions/backend/integration/backend-cicd@main
        with:
          env-name: prod
          service-name: minileague-calendar-batch
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          java-version: 21
          distribution: temurin
          working-directory: module-batch
          build-command: ./gradlew :module-batch:clean :module-batch:test :module-batch:bootJar
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker-repository: mrcocoball/minileague-calendar-batch
          tag-prefix: prod
          dockerfile-directory: module-batch
          gitops-repository: git@github.com:doriball/minileague-calendar-infrastructure.git
          gitops-branch: main
          gitops-values-directory: environments/prod/apps/batch-values.yml
          ssh-key: ${{ secrets.GITOPS_SSH_KEY }}
          commit-message: "chore: batch prod image update"
